USE [ToDoAppDB]
GO

/****** Object:  Table [dbo].[ToDoList]    Script Date: 27-03-2021 14:07:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ToDoList](
	[ToDoListId] [int] IDENTITY(1,1) NOT NULL,
	[ToDoListName] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ToDoListId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


